# Codacy configuration for Godyar CMS (v1.11)
# Notes:
# - This project is NOT WordPress. Input/escaping rules differ.
# - We exclude template-heavy folders to reduce false positives and noisy duplication/complexity signals.
exclude_paths:
  - "vendor/**"
  - "storage/**"
  - "cache/**"
  - "logs/**"
  - "uploads/**"
  - "webroot/uploads/**"
  - "assets/uploads/**"

  - "frontend/views/**"
  - "frontend/templates/**"
  - "admin/frontend/views/**"
  - "admin/**/views/**"

  - "tools/**"
  - "oauth/**"
  - "seo/**"
  - "sitemap*.php"
  - "rss*.php"
  - "og_image.php"

  - ".github/**"
  - "**/*.min.js"
  - "**/*.min.css"
